name: Python CI

# Trigger the workflow on push or pull requests to specific session folders in the main branch
on:
  push:
    branches:
      - main
    paths:
      - 'session-17/**'
      - 'session-18/**'
  pull_request:
    branches:
      - main
    paths:
      - 'session-17/**'
      - 'session-18/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.11']
        session-folder: ['session-17', 'session-18']

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ matrix.session-folder }}/requirements.txt

    - name: Run tests for session-17
      if: matrix.session-folder == 'session-17' && contains(github.event.head_commit.modified, 'session-17/') || contains(github.event.pull_request.title, 'session-17')
      run: |
        cd session-17
        pytest test_merge.py test_validate.py

    - name: Run tests for session-18
      if: matrix.session-folder == 'session-18' && contains(github.event.head_commit.modified, 'session-18/') || contains(github.event.pull_request.title, 'session-18')
      run: |
        cd session-18
        pytest assignment_test.py