name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - 'session-17/**'
      - 'session-18/**'
  pull_request:
    branches:
      - main
    paths:
      - 'session-17/**'
      - 'session-18/**'

jobs:
  test-session-17:
    if: contains(github.event.head_commit.modified, 'session-17/') || contains(github.event.pull_request.title, 'session-17')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r session-17/requirements.txt
    - name: Run tests
      run: |
        cd session-17
        pytest test_merge.py test_validate.py

  test-session-18:
    if: contains(github.event.head_commit.modified, 'session-18/') || contains(github.event.pull_request.title, 'session-18')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r session-18/requirements.txt
    - name: Run tests
      run: |
        cd session-18
        pytest assignment_test.py